spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-client-id
            client-secret: your-client-secret
          github:
            client-id: your-client-id
            client-secret: your-client-secret
          okta:
            client-id: your-client-id
            client-secret: your-client-secret
        provider:
          okta:
            authorization-uri: https://dev-169923.okta.com/oauth2/v1/authorize
            token-uri: https://dev-169923.okta.com/oauth2/v1/token
            user-info-uri: https://dev-169923.okta.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://dev-169923.okta.com/oauth2/v1/keys
  thymeleaf:
    cache: false
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
