spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-client-id-obtained-from-google-api-console
            client-secret: your-client-secret-obtained-from-google-api-console
  thymeleaf:
    cache: false
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
