spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-client-id-from-google
            client-secret: your-client-secret-from-google
          github:
            client-id: your-client-id-from-github
            client-secret: your-client-secret-from-github
          okta:
            client-id: your-client-id-from-okta
            client-secret: your-client-secret-from-okta
        provider:
          okta:
            authorization-uri: https://dev-169923.okta.com/oauth2/v1/authorize
            token-uri: https://dev-169923.okta.com/oauth2/v1/token
            user-info-uri: https://dev-169923.okta.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://dev-169923.okta.com/oauth2/v1/keys
  thymeleaf:
    cache: false
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
